### ISSUE TITLE
Can't install the SDK

### ISSUE THREAD

**Issue by Hirbod** [adjust/cordova_sdk#18]
Hi guys,

I was so suprised that you offer a Cordova SDK, but sadly, I can't install it. I receive following error:

```
Hirbods-MacBook-Pro-Retina:Nachbarschaft Hirbod$ cordova plugin add cordova_sdk
Installing "com.adjust.sdk" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.adjust.sdk':Error: Uh oh!
"/Users/Hirbod/Desktop/appdev/Nachbarschaft/plugins/com.adjust.sdk/src/android/Adjust/Adjust/src/com/adjust/sdk" not found!
    at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:43:40)
    at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:72:16)
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:65:20)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Uh oh!
"/Users/Hirbod/Desktop/appdev/Nachbarschaft/plugins/com.adjust.sdk/src/android/Adjust/Adjust/src/com/adjust/sdk" not found!
    at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:43:40)
    at Object.module.exports.common.copyNewFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:72:16)
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:65:20)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
```

What can I do? Cordova 3.7.0 for iOS and Cordova 3.6.3 for Android.

**Comment by Hirbod** [comment]
Sorry Folks,

it was my fault. Did not read the documentation clearly. I've downloaded the master instead of grabbing the "release" files. Installation worked fine now.
