### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by kiliankoller** [adjust/cordova_sdk#45]
Hi, when I execute
`cordova plugin add com.adjust.sdk`

I get the following error:

```
Installing "com.adjust.sdk" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.adjust.sdk':CordovaError: Uh oh!
"/Users/kkoller/Documents/treefin/git/app/dist_cordova/plugins/com.adjust.sdk/src/Android/adjust-android.jar" not found!
    at copyFile (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/lib/pluginHandlers.js:202:36)
    at copyNewFile (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/lib/pluginHandlers.js:234:5)
    at handlers.source-file.install (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/lib/pluginHandlers.js:37:17)
    at Object.ActionStack.process (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/kkoller/Documents/treefin/git/app/dist_cordova/platforms/android/cordova/Api.js:198:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
"/Users/kkoller/Documents/treefin/git/app/dist_cordova/plugins/com.adjust.sdk/src/Android/adjust-android.jar" not found!

```
Thanks for solving!

**Comment by uerceg** [comment]
Thanks for reporting, we're on it.

**Comment by uerceg** [comment]
@kiliankoller Can you please retry now?

**Comment by kiliankoller** [comment]
@uerceg Looks good now! I still had Cordova Android 5.X installed, nor 6.X. Thanks!
